//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timesheets
{


    public partial class ThisAddIn : Microsoft.Office.Tools.Outlook.OutlookAddInBase
    {

        internal ThisAddIn(global::Microsoft.Office.Tools.Outlook.Factory factory, global::System.IServiceProvider serviceProvider) :
                base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void Initialize()
        {
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeData();
            this.InitializeControls();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void FinishInitialization()
        {
            this.InternalStartup();
            this.OnStartup();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeDataBindings()
        {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData()
        {
            if ((this.DataHost == null))
            {
                return;
            }
            if (this.DataHost.IsCacheInitialized)
            {
                this.DataHost.FillCachedData(this);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData()
        {
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData()
        {
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls()
        {
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InternalStartup()
        {
            this.Startup += new System.EventHandler(this.ThisAddIn_Startup);
            this.Shutdown += new System.EventHandler(this.ThisAddIn_Shutdown);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnShutdown()
        {
            this.Shutdown -= new System.EventHandler(this.ThisAddIn_Shutdown);
            this.Startup -= new System.EventHandler(this.ThisAddIn_Startup);
            base.OnShutdown();
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Globals
    {

        private static ThisAddIn _ThisAddIn;

        private static global::Microsoft.Office.Tools.Outlook.Factory _factory;

        private static ThisAddInRibbonFactory _RibbonFactory;

        internal static ThisAddIn ThisAddIn
        {
            get
            {
                return _ThisAddIn;
            }
            set
            {
                if ((_ThisAddIn == null))
                {
                    _ThisAddIn = value;
                }
                else
                {
                    throw new System.NotSupportedException();
                }
            }
        }

        internal static global::Microsoft.Office.Tools.Outlook.Factory Factory
        {
            get
            {
                return _factory;
            }
            set
            {
                if ((_factory == null))
                {
                    _factory = value;
                }
                else
                {
                    throw new System.NotSupportedException();
                }
            }
        }

        internal static ThisAddInRibbonFactory RibbonFactory
        {
            get
            {
                return _RibbonFactory;
            }
            set
            {
                if ((_RibbonFactory == null))
                {
                    _RibbonFactory = value;
                }
                else
                {
                    throw new System.NotSupportedException();
                }
            }
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal sealed partial class ThisAddInRibbonFactory : Microsoft.Office.Tools.Ribbon.RibbonFactory
    {

        internal ThisAddInRibbonFactory(global::Microsoft.Office.Tools.Outlook.Factory factory) :
                base(factory)
        {
        }
    }
}
